defaults:
  - dataset: new_york_port

common:
  seed: 200
  device: cpu

dataset:
  new_york_port:
      dataset_name: NewYork_port
      max_initial_steps: 5  # number of initial training epochs
      max_steps: 10  # number of main training epochs
      batch_size: 16
      patience: 150
      lr: 1e-3
      window_size: 25
      hidden_size: 256
      run_dir: ./experiment/new_york_port
